# Generated by Django 6.0.6 on 2026-07-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculationhistory",
            name="performed_by",
            field=models.CharField(default="", max_length=255),
        ),
    ]
